Multi_Agent.Web/Controllers/PolicyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Multi_Agent.Application.Interfaces;
using Multi_Agent.Application.Services;
using Multi_Agent.Application.ViewModels.Employee;
using Multi_Agent.Application.ViewModels.Policy;
using System.Drawing;

namespace Multi_Agent.Web.Controllers
{
    public class PolicyController : Controller
    {
        private readonly IPolicyService _policyService;
        private readonly ICustomerService _customerService;
        private readonly IInsuranceCompanyService _insuranceCompanyService;
        private readonly IEmployeeService _employeeService;
        public PolicyController(IPolicyService policyService, ICustomerService customerService,
            IInsuranceCompanyService insuranceCompanyService, IEmployeeService employeeService)
        {
            _policyService = policyService;
            _customerService = customerService;
            _insuranceCompanyService = insuranceCompanyService;
            _employeeService = employeeService;
        }


        [HttpGet]
        public IActionResult Index()
        {
            //utworzyć wido dla tej akcji
            //tabla z kLientami 
            //filtorwanie danych
            //przekazać filtry do serwisu
            //serwis przygotuje dane
            //serwis musi zwrócić dane w odpowiednim formacie

            var model = _policyService.GetAllPoliciesForList(8, 1, "");

            return View(model);
        }


        [HttpPost]
        public IActionResult Index(int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }

            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var model = _policyService.GetAllPoliciesForList(pageSize, pageNo.Value, searchString);
            return View(model);
        }

        [HttpGet]
        public IActionResult AddPolicy()
        {
            ViewData["CustomerId"] = new SelectList(_customerService.GetAllCustomersForList().Customers, "Id", "FullName");
            ViewData["PolicyStatusId"] = new SelectList(_policyService.GetAllPolicyStatusesForList(), "Id", "Name");
            ViewData["PolicyTypeId"] = new SelectList(_policyService.GetAllPolicyTypesForList(), "Id", "Name");
            ViewData["PaymentTypeId"] = new SelectList(_policyService.GetAllPaymentTypesForList(), "Id", "Name");
            ViewData["InsuranceCompanyId"] = new SelectList(_insuranceCompanyService.GetAllInsuranceCompanyForList().InsuranceCompanies, "Id", "Name");
            ViewData["AgentId"] = new SelectList(_employeeService.GetActiveAgentsList(), "Id", "FullName");
            ViewBag.PolicyDate = DateTime.Today.ToShortDateString();
            ViewBag.PolicyDateEnd = DateTime.Today.AddYears(1).AddDays(-1).ToShortDateString(); 
            ViewBag.PolicyDateStart = DateTime.Today.ToShortDateString(); 
            return View(new NewPolicyVm());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddPolicy(NewPolicyVm model)
        {
            var id = _policyService.AddPolicy(model);
            return RedirectToAction("Index");
        }


        public IActionResult ViewPolicy(int Id)
        {
            var model = _policyService.GetPolicyDetails(Id);
            return View(model);
        }

        [HttpGet]
        public IActionResult EditPolicy(int id)
        {
            var policy = _policyService.GetPolicyForEdit(id);
            if (policy == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_customerService.GetAllCustomersForList().Customers, "Id", "FullName");
            ViewData["PolicyStatusId"] = new SelectList(_policyService.GetAllPolicyStatusesForList(), "Id", "Name");
            ViewData["PolicyTypeId"] = new SelectList(_policyService.GetAllPolicyTypesForList(), "Id", "Name");
            ViewData["PaymentTypeId"] = new SelectList(_policyService.GetAllPaymentTypesForList(), "Id", "Name");
            ViewData["InsuranceCompanyId"] = new SelectList(_insuranceCompanyService.GetAllInsuranceCompanyForList().InsuranceCompanies, "Id", "Name");
            ViewData["AgentId"] = new SelectList(_employeeService.GetActiveAgentsList(), "Id", "FullName");
            return View(policy);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPolicy(NewPolicyVm model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _policyService.UpdatePolicy(model);
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (model != null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return View(model);
        }

        public IActionResult DeletePolicy(int id)
        {
            _policyService.DeletePolicy(id);
            return RedirectToAction("Index");
        }
    }
}

Multi_Agent.Web/Views/Policy/AddPolicy.cshtml
@model Multi_Agent.Application.ViewModels.Policy.NewPolicyVm

@{
    ViewData["Title"] = "AddPolicy";
}

<h1>Dodaj nową polisę</h1>

<h4></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPolicy">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="CreatedAt" />
        <input type="hidden" asp-for="CreatedBy" />
        <input type="hidden" asp-for="IsActive" />
            <div class="form-group">
                <label class="control-label">Numer Polisy</label>
                <input asp-for="PolicyNumber" class="form-control" />
                <span asp-validation-for="PolicyNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Numer rejestracyjny</label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Data Polisy</label>
                <input asp-for="PolicyDate" class="form-control" value = "@ViewBag.PolicyDate"/>
                <span asp-validation-for="PolicyDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Okres polisy OD</label>
                <input asp-for="PolicyDateStart" class="form-control" value="@ViewBag.PolicyDateStart" />
                <span asp-validation-for="PolicyDateStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Okres polisy DO </label>
                <input asp-for="PolicyDateEnd" class="form-control" value = "@ViewBag.PolicyDateEnd" />
                <span asp-validation-for="PolicyDateEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Przypis</label>
                <input asp-for="Premium" class="form-control" />
                <span asp-validation-for="Premium" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Inkaso</label>
                <input asp-for="PremiumPaid" class="form-control" />
                <span asp-validation-for="PremiumPaid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Klient</label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId">  </select>
            </div>
            <div class="form-group">
                <label class="control-label">Towarzystwo ubezpieczeniowe</label>
                <select asp-for="InsuranceCompanyId" class="form-control" asp-items="ViewBag.InsuranceCompanyId">  </select>
                <span asp-validation-for="InsuranceCompanyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Rodzaj płatności</label>
                <select asp-for="PaymentTypeId" class="form-control" asp-items="ViewBag.PaymentTypeId"> </select>
                <span asp-validation-for="PaymentTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Rodzaj polisy</label>
                <select asp-for="PolicyTypeId" class="form-control" asp-items="ViewBag.PolicyTypeId"> </select>
                <span asp-validation-for="PolicyTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Status polisy</label>
                <select asp-for="PolicyStatusId" class="form-control" asp-items="ViewBag.PolicyStatusId"> </select>
                <span asp-validation-for="PolicyStatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AgentId" class="control-label"></label>
                <select asp-for="AgentId" class="form-control" asp-items="ViewBag.AgentId"> </select>
                <span asp-validation-for="AgentId" class="text-danger"></span>
            </div>
@*            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>*@

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Multi_Agent.Web/Views/Policy/EditPolicy.cshtml
@model Multi_Agent.Application.ViewModels.Policy.NewPolicyVm

@{
    ViewData["Title"] = "EditPolicy";
}

<h1>Edytuj Polisę</h1>

<h4></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPolicy">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label class="control-label">Numer Polisy</label>
                <input asp-for="PolicyNumber" class="form-control" />
                <span asp-validation-for="PolicyNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Numer rejestracyjny</label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Data Polisy</label>
                <input asp-for="PolicyDate" class="form-control" />
                <span asp-validation-for="PolicyDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Okres polisy OD</label>
                <input asp-for="PolicyDateStart" class="form-control" />
                <span asp-validation-for="PolicyDateStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Okres polisy DO</label>
                <input asp-for="PolicyDateEnd" class="form-control" />
                <span asp-validation-for="PolicyDateEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Przypis</label>
                <input asp-for="Premium" class="form-control" />
                <span asp-validation-for="Premium" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Inkaso</label>
                <input asp-for="PremiumPaid" class="form-control" />
                <span asp-validation-for="PremiumPaid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Klient</label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId">  </select>
            </div>
            <div class="form-group">
                <label class="control-label">Towarzystwo ubezpieczeniowe</label>
                <select asp-for="InsuranceCompanyId" class="form-control" asp-items="ViewBag.InsuranceCompanyId">  </select>
                <span asp-validation-for="InsuranceCompanyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Rodzaj płatności</label>
                <select asp-for="PaymentTypeId" class="form-control" asp-items="ViewBag.PaymentTypeId"> </select>
                <span asp-validation-for="PaymentTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Rodzaj polisy</label>
                <select asp-for="PolicyTypeId" class="form-control" asp-items="ViewBag.PolicyTypeId"> </select>
                <span asp-validation-for="PolicyTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Status polisy</label>
                <select asp-for="PolicyStatusId" class="form-control" asp-items="ViewBag.PolicyStatusId"> </select>
                <span asp-validation-for="PolicyStatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AgentId" class="control-label"></label>
                <select asp-for="AgentId" class="form-control" asp-items="ViewBag.AgentId"> </select>
                <span asp-validation-for="AgentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="CreatedAt" />
                <input type="hidden" asp-for="ModifiedAt" />
                <input type="hidden" asp-for="CreatedBy" />
                <input type="hidden" asp-for="ModifiedBy" />
                <input type="hidden" asp-for="IsActive" />
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Ewidencja Polis</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Multi_Agent.Web/Views/Policy/Index.cshtml
@model Multi_Agent.Application.ViewModels.Policy.ListPolicyForListVm

@{
    ViewData["Title"] = "Index";
}

<h1>Kartoteka Polis</h1>

<p>
    <a asp-action="AddPolicy">Dodaj polisę</a>
</p>
<form asp-action="Index" asp-controller="Policy" method="post">
    <div class="row">
        <input type="text" asp-for="SearchString" name="searchString" id="saerachString" placeholder="Wprowadź szukaną frazę ..." />
        <input type="submit" value="Wyszukaj" />
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        Numer polisy
                    </th>
                    <th>
                        Nazwa Klienta
                    </th>
                    <th>
                        Nazwa Towarzystwa ubezpieczeniowego
                    </th>
                    <th>
                        Status polisy
                    </th>
                    <th>
                        Rodzaj polisy
                    </th>
                    <th>
                        Przypis
                    </th>
                    <th>
                        Okres polisy od
                    </th>
                    <th>
                        Okres polisy do
                    </th>
                    <th>
                        Rodzaj płatności
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Policies)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PolicyNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CustomerFullName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.InsuranceCompanyName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PolicyStatusName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PolicyTypeName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Premium)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PolicyDateStart)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PolicyDateEnd)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PaymentTypeName)
                        </td>

                        <td>
                            @Html.ActionLink("Szczegóły", "ViewPolicy", new {  id=item.Id  }) |
                            @Html.ActionLink("Usuń", "DeletePolicy", new {  id=item.Id  },
                new { onclick = "return confirm('Czy napewno chcesz usunąć polisę Id: " + @item.Id + "?')" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="row">
        <table>
            <tr>
                @for (int i = 1; i <= Math.Ceiling(Model.Count / (double)Model.PageSize); i++)
                {
                    <td>
                        @if (i != Model.CurrentPage)
                        {
                            <a href="javascript:PagerClick(@i)">@i</a>
                        }
                        else
                        {
                            <span>@i</span>
                        }
                    </td>

                }
            </tr>
        </table>
        <input type="hidden" name="pageNo" id="pageNo" />
        <input type="hidden" name="pageSize" id="pageSize" value="8" />
    </div>

</form>

@section Scripts
    {
    <script type="text/javascript">
        function PagerClick(index) {
            document.getElementById("pageNo").value = index;
            document.forms[0].submit();
        }

    </script>

}

Multi_Agent.Web/Views/Policy/ViewPolicy.cshtml
@model Multi_Agent.Application.ViewModels.Policy.PolicyDetailsVm

@{
    ViewData["Title"] = "ViewPolicy";
}

<h1>Szczegóły Polisy</h1>

<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PolicyNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PolicyNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PolicyStatusName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PolicyStatusName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PolicyTypeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PolicyTypeName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Premium)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Premium)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PremiumPaid)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PremiumPaid)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentTypeName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PaymentTypeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerFullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerFullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InsuranceCompanyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InsuranceCompanyName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AgentFullName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AgentFullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PolicyDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PolicyDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PolicyDateStart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PolicyDateStart)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PolicyDateEnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PolicyDateEnd)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedAt)
        </dd>

    </dl>
</div>
<div>
    @Html.ActionLink("Edytuj", "EditPolicy", new { id = Model.Id }) |
    <a asp-action="Index">Kartoteka Polis</a>
</div>